### ISSUE TITLE
Issue with importing TimedJSONWebSignatureSerializer when updating db with Flask.

### ISSUE THREAD

**Issue by TheLostProgrammer** [pallets/itsdangerous#318] opened 2022-11-01 13:56 UTC
```
flask db upgrade
Usage: flask db upgrade [OPTIONS] [REVISION]
Try 'flask db upgrade --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/lostprogrammer/Documents/Documents/website/app.py", line 7, in <module>
    from models import db
  File "/Users/lostprogrammer/Documents/Documents/website/models.py", line 2, in <module>
    from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/itsdangerous/__init__.py)
```
I am getting this error when trying to update my database.  I am honestly unsure of the exact reason behind this.

Replicate the bug:
- Using macOS Ventura
- Python 3.9.10 with flask 2.2.2. 
- Setup a flask web server with a basic PostgreSQL database
Add the following line to the Python file:
```py
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
```
- Run `flask db upgrade` in said Python file

Expected behaviour:
From the many times I have used `flask db upgrade` and `flask db migrate`, this time I was not very lucky and received an odd error.

Environment:

- Python version: Python 3.9.10
- ItsDangerous version: 2.0.1
- Flask version: 2.2.2

**Comment by davidism** [comment] 2022-11-01 13:57
Duplicate of #294

**Closed by davidism** 2022-11-01 13:57 UTC
