### ISSUE TITLE
'Signer' Example from Website does not work with Python 3.6

### ISSUE THREAD

**Issue by feluxe** [pallets/itsdangerous#94] opened 2017-11-16 10:18 UTC
Hi there!

I just tried the example from the website:
```
>>> from itsdangerous import Signer
>>> s = Signer('secret-key')
>>> s.sign('my string')
```
If I enter it in a Python 3.6 REPL, it produces this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/share/virtualenvs/backend-nswOXq5B/lib/python3.6/site-packages/itsdangerous.py", line 353, in sign
    return value + want_bytes(self.sep) + self.get_signature(value)
TypeError: must be str, not bytes
```

**Comment by ThiefMaster** [comment] 2017-11-16 10:21
duplicate of #89

**Closed by ThiefMaster** 2017-11-16 10:21 UTC
