### ISSUE TITLE
Document that itsdangerous does not follow semver

### ISSUE THREAD

**Issue by ShaneHarvey** [pallets/itsdangerous#293] opened 2022-02-24 23:32 UTC
Like many other users, I recently ran into the "ImportError: cannot import name 'json' from 'itsdangerous' " error issue caused by the change in v2.1.0.

It would be helpful to document that itsdangerous' versioning scheme and highlight that it does not follow Semantic Versioning.

**Comment by davidism** [comment] 2022-02-25 00:59
I am not optimistic that this would have changed anything. The issue is not semver, its that people aren't pinning their dependencies. That said, I've had a draft for the website from well before this, but just need to finish it. Since it's not specific to itsdangerous, I'm going to close this issue.

**Closed by davidism** 2022-02-25 00:59 UTC

**Comment by ShaneHarvey** [comment] 2022-02-25 01:19
Thanks! As for the pinning, sure pinning is best practice but I believe one goal of a library maintainer should be to ensure that `pip install lib==1.1.1` continues to work as long as the dependencies it uses correctly follow semver. It's a useful property and one that many users expect to work. Breaking this goal always leads to user pain and actually makes it _harder_ for users to pin (and later upgrade) their own dependencies. When `pip install lib==1.1.1` fetches incompatible dependencies the user is forced to wade through obscure errors, read changelogs, etc. just to find the right version to pin to.
